USE FINANCEIRA;
INSERT INTO tbl_empresa VALUES(1, 'Mcdonals', 1);
INSERT INTO tbl_empresa VALUES(2, 'Burguer king', 1);
INSERT INTO tbl_empresa VALUES(3, 'Girafas', 1);
INSERT INTO tbl_empresa VALUES(4, 'Uber', 2);
INSERT INTO tbl_empresa VALUES(5, '99 taxis', 2);
INSERT INTO tbl_empresa VALUES(6, 'Americanas', 3);
INSERT INTO tbl_empresa VALUES(7, 'Extra', 3);
INSERT INTO tbl_empresa VALUES(8, 'Daiso', 3);
INSERT INTO tbl_empresa VALUES(9, 'Udemy', 4);
INSERT INTO tbl_empresa VALUES(10, 'Alura', 4);
INSERT INTO tbl_empresa VALUES(11, 'Steam', 5);
INSERT INTO tbl_empresa VALUES(12, 'Psn', 5);
INSERT INTO tbl_empresa VALUES(13, 'Xbox Live', 5);